JAVAC=javac
JAVA=java
SRC=src
BIN=bin
JAR=StoreApp.jar

all: compile jar

compile:
    mkdir -p $(BIN)
    $(JAVAC) -d $(BIN) $(SRC)/*.java

jar:
    echo Main-Class: your.main.Class > Manifest.txt
    jar cfm $(JAR) Manifest.txt -C $(BIN) .
    rm Manifest.txt

clean:
    rm -rf $(BIN)/*.class
    rm -rf $(JAR)

.PHONY: compile jar clean
