JAVAC = javac
JAVA = java
SRC_DIR = src
BIN_DIR = bin
SERVER_CLASS = StoreServer
CLIENT_CLASS = StoreClient
RMI_PORT = 1099


compile:
    mkdir -p $(BIN_DIR)
    $(JAVAC) -d $(BIN_DIR) $(SRC_DIR)/*.java


run-server:
    $(JAVA) -cp $(BIN_DIR) $(SERVER_CLASS)


run-client:
    $(JAVA) -cp $(BIN_DIR) $(CLIENT_CLASS)


clean:
    rm -rf $(BIN_DIR)/*

# Start RMI registry
start-rmi:
    rmiregistry $(RMI_PORT)

